package interfaz;

import vistas.VistaIniciar_sesion_con_aplicacion_de_terceros;

public class Iniciar_sesion_con_aplicacion_de_terceros extends VistaIniciar_sesion_con_aplicacion_de_terceros {
	public Iniciar_sesion _iniciar_sesion;
	public Servicio_de_autenticacion_externo _unnamed_Servicio_de_autenticacion_externo_;
}